services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}

    restart: unless-stopped

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - management_net

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./config:/config:ro
      - ./certs:/certs:ro
      - ./acme:/acme

networks:
  management_net:
    external: true