http:
  routers:
    traefik:
      rule: "Host(`traefik.homelab.msaquib.com`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: api@internal

    cockpit:
      rule: "Host(`cockpit.homelab.msaquib.com`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: cockpit

  services:
    cockpit:
      loadBalancer:
        servers:
          - url: "https://host.docker.internal:9090"
        serversTransport: cockpitTransport

  serversTransports:
    cockpitTransport:
      insecureSkipVerify: true

# tls:
#   certificates:
#     - certFile: /certs/homelab.crt
#       keyFile: /certs/homelab.key