http:
  routers:
    traefik:
      rule: "Host(`traefik.homelab.msaquib.com`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      middlewares:
        - github-auth
      service: api@internal

    cockpit:
      rule: "Host(`cockpit.homelab.msaquib.com`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      middlewares:
        - github-auth
      service: cockpit

  services:
    cockpit:
      loadBalancer:
        servers:
          - url: "https://host.docker.internal:9090"
        serversTransport: cockpitTransport

    oauth2-proxy-svc:
      loadBalancer:
        servers:
          - url: "http://oauth2-proxy:4180"

  middlewares:
    auth-signin:
      errors:
        status:
          - "401"
        service: oauth2-proxy-svc
        query: "/oauth2/sign_in?rd={url}"

    auth-verify:
      forwardAuth:
        address: "http://oauth2-proxy:4180/oauth2/auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Auth-Request-User"
          - "X-Auth-Request-Email"
          - "X-Auth-Request-Access-Token"

    github-auth:
      chain:
        middlewares:
          - auth-signin
          - auth-verify

  serversTransports:
    cockpitTransport:
      insecureSkipVerify: true

# tls:
#   certificates:
#     - certFile: /certs/homelab.crt
#       keyFile: /certs/homelab.key