services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer

    restart: unless-stopped

    networks:
      - management_net
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.homelab.msaquib.com`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=cloudflare
      - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  management_net:
    external: true
